---
title: "避難場所がどこか、Rで確認してみよう"
author: "伊東宏樹"
date: 2025-11-15
lang: ja
format: revealjs
execute: 
  echo: true
code-line-numbers: true
embed-resources: true
editor: visual
---

```{r}
#| label: setup
#| output: false

library(tidyverse)
```

## 自己紹介

伊東宏樹

## この発表の目的

指定緊急避難場所

Rをつかって

マウスなどで移動・拡大縮小ができる地図上に緊急避難場所を配置して、



## 指定緊急避難場所とは

-   **指定緊急避難場所**: 災害の危険から命を守るために緊急的に避難する場所

    -   土砂災害、洪水、津波、地震等の災害種別ごとに指定が行われる

-   **指定避難所**: 災害が発生した場合に避難をしてきた被災者が一定期間生活するための施設

::: {style="font-size: 80%;"}
内閣府: [「指定緊急避難場所」と「指定避難所」の違いについて](https://www.bousai.go.jp/taisaku/pdf/hinanjo_02.pdf)
:::

## データ

[金沢市オープンデータポータル](https://catalog-data.city.kanazawa.ishikawa.jp/about)から[石川中央都市圏 指定緊急避難場所一覧](https://catalog-data.city.kanazawa.ishikawa.jp/dataset/ishikawa-central-evacuation-space)のCSVファイルをダウンロード

```{r}
#| label: read_data
#| output: false

data_dir <- "data"
data_file <- "ishikawa-central-evacuation-space.csv"
data <- read_csv(file.path(data_dir, data_file))
```

## データ確認

```{r}
#| label: view_data

data
```

## 列の確認

```{r}
colnames(data)
```

## 地震の緊急避難場所を抽出

```{r}
earthquake <- data |>
  dplyr::filter(`災害種別_地震` == 1)
```

## 数を比較

```{r}
nrow(data)
nrow(earthquake)
```

## Leaflet

インタラクティブな地図を作成できる

```{r}
library(leaflet)
```

## 表示例

```{r}
#| message: false

leaflet() |>
  addTiles() # デフォルトでOpenStreetMapを表示
```

## 金沢駅付近

```{r}
#| eval: false

# 金沢駅の位置
lat <- 36.578044
lng <- 136.648175

leaflet() |>
  addTiles() |>
  setView(lng = lng, lat = lat, zoom = 15)
```

------------------------------------------------------------------------

```{r}
#| echo: false

# 金沢駅の位置
lat <- 36.578044
lng <- 136.648175

leaflet() |>
  addTiles() |>
  setView(lng = lng, lat = lat, zoom = 15)
```

## 避難場所のマーカーを追加

```{r}
#| eval: false
leaflet() |>
  addTiles() |>
  setView(lng = lng, lat = lat, zoom = 15) |>
  addMarkers(lng = ~`経度`, lat = ~`緯度`,
             data = earthquake)
```

------------------------------------------------------------------------

```{r}
#| echo: false

leaflet() |>
  addTiles() |>
  setView(lng = lng, lat = lat, zoom = 15) |>
  addMarkers(lng = ~`経度`, lat = ~`緯度`,
             data = earthquake)
```

## マーカーに説明を追加

```{r}
#| eval: false
leaflet() |>
  addTiles() |>
  setView(lng = lng, lat = lat, zoom = 15) |>
  addMarkers(lng = ~`経度`, lat = ~`緯度`,
             popup = ~`名称` |> htmltools::htmlEscape(),
             data = earthquake)
```

------------------------------------------------------------------------

マーカーをクリックすると、避難場所の名称が表示される

```{r}
#| echo: false

leaflet() |>
  addTiles() |>
  setView(lng = lng, lat = lat, zoom = 15) |>
  addMarkers(lng = ~`経度`, lat = ~`緯度`,
             popup = ~`名称` |> htmltools::htmlEscape(),
             data = earthquake)
```

## まとめ
